upstream unicorn {
    server unix:/var/www/cdp_web_web_aws_deploy_task/current/tmp/sockets/unicorn.sock;
}

server {
        listen 80;
        server_name 34.238.75.149;
        root /var/www/cdp_web_web_aws_deploy_task/current/public;
        access_log /var/log/nginx/cdp_web_web_aws_deploy_task_access.log;
        error_log /var/log/nginx/cdp_web_web_aws_deploy_task_error.log;

        location ~ ^/assets/ {
        }

        location ~ ^/packs/ {
        }

        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_pass http://unicorn;
        }
}
